
if(${ENABLE_DOUBLE})
	set_property(TARGET ${PROJECT_NAME} APPEND PROPERTY COMPILE_DEFINITIONS "USE_DOUBLE=${ENABLE_DOUBLE}")
endif()
#target_compile_definitions(${PROJECT_NAME} PUBLIC ENABLE_DOUBLE=${ENABLE_DOUBLE})

if(${ENABLE_64BIT_IDS})
	set_property(TARGET ${PROJECT_NAME} APPEND PROPERTY COMPILE_DEFINITIONS "USE_LONGLONG=${ENABLE_64BIT_IDS}")
endif()